modLoader = "kotlinforforge"
loaderVersion = "[3,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "fgwithlm"
version = "${version}"
displayName = "FlexibleGuns with LittleMaid"
authors = "Sistr"
description = "FlexibleGunsの銃をメイドさんが扱えるようになるModです。"
#logoFile = ""

[[dependencies.fgwithlm]]
modId = "forge"
mandatory = true
versionRange = "[39,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fgwithlm]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fgwithlm]]
modId = "architectury"
mandatory = true
versionRange = "[3.2.49,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.fgwithlm]]
modId = "flexibleguns"
mandatory = true
versionRange = "[1.4.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.fgwithlm]]
modId = "littlemaidmodelloader"
mandatory = true
versionRange = "[2.1.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.fgwithlm]]
modId = "littlemaidrebirth"
mandatory = true
versionRange = "[2.1.0,)"
ordering = "AFTER"
side = "BOTH"